// src/ui/app/login/page.tsx
'use client';

import { useState } from 'react';
import { useRouter } from 'next/navigation';
import { useAuth } from '@/lib/stores/auth';
import { api } from '@/lib/api';

export default function LoginPage() {
	const { setToken } = useAuth();
	const router = useRouter();
	const [email, setEmail] = useState('');
	const [password, setPassword] = useState('');
	const [name, setName] = useState('');
	const [activeTab, setActiveTab] = useState<'login' | 'register'>('login');
	const [loading, setLoading] = useState(false);
	const [error, setError] = useState('');

	async function handleLogin() {
		if (!email || !password) {
			setError('Please enter email and password');
			return;
		}

		setLoading(true);
		setError('');

		try {
			const response = await api.post<{ token: string; user: any }>('/api/v1/auth/login', {
				email,
				password,
			});

			await setToken(response.token);
			router.push('/');
		} catch (e: any) {
			setError(e.message || 'Login failed. Please try again.');
		} finally {
			setLoading(false);
		}
	}

	async function handleRegister() {
		if (!email || !password || !name) {
			setError('Please fill in all fields');
			return;
		}

		if (password.length < 6) {
			setError('Password must be at least 6 characters');
			return;
		}

		setLoading(true);
		setError('');

		try {
			const response = await api.post<{ token: string; user: any }>('/api/v1/auth/register', {
				email,
				password,
				name,
			});

			await setToken(response.token);
			router.push('/');
		} catch (e: any) {
			setError(e.message || 'Registration failed. Please try again.');
		} finally {
			setLoading(false);
		}
	}

	return (
		<div className="min-h-screen flex items-center justify-center bg-purple-600 p-8">
			<div className="bg-white rounded-xl shadow-xl w-full max-w-md p-10">
				<div className="mb-8">
					<div className="flex items-center gap-3 mb-2">
						<img src="/gopher.png" alt="AlgoShield" className="w-12 h-12 object-contain" />
						<h1 className="text-3xl font-semibold text-gray-900">AlgoShield</h1>
					</div>
					<p className="text-sm text-gray-500">Fraud Detection & Anti-Money Laundering</p>
				</div>

				<div className="flex gap-2 mb-6 border-b-2 border-gray-200">
					<button
						onClick={() => {
							setActiveTab('login');
							setError('');
						}}
						className={`flex-1 py-3 text-sm font-medium transition-all border-b-2 -mb-[2px] ${
							activeTab === 'login'
								? 'text-indigo-600 border-indigo-600 font-semibold'
								: 'text-gray-500 border-transparent'
						}`}
					>
						Login
					</button>
					<button
						onClick={() => {
							setActiveTab('register');
							setError('');
						}}
						className={`flex-1 py-3 text-sm font-medium transition-all border-b-2 -mb-[2px] ${
							activeTab === 'register'
								? 'text-indigo-600 border-indigo-600 font-semibold'
								: 'text-gray-500 border-transparent'
						}`}
					>
						Register
					</button>
				</div>

				{error && (
					<div className="bg-red-50 border border-red-200 rounded-md p-3 mb-6 text-sm text-red-600">
						{error}
					</div>
				)}

				{activeTab === 'login' ? (
					<form
						onSubmit={(e) => {
							e.preventDefault();
							handleLogin();
						}}
						className="space-y-6"
					>
						<div>
							<label htmlFor="email" className="block text-sm font-medium text-gray-700 mb-2">
								Email
							</label>
							<input
								id="email"
								type="email"
								value={email}
								onChange={(e) => setEmail(e.target.value)}
								placeholder="user@example.com"
								required
								disabled={loading}
								className="w-full px-4 py-3 border border-gray-300 rounded-md focus:outline-none focus:ring-2 focus:ring-indigo-500 focus:border-transparent disabled:opacity-60 disabled:cursor-not-allowed"
							/>
						</div>

						<div>
							<label htmlFor="password" className="block text-sm font-medium text-gray-700 mb-2">
								Password
							</label>
							<input
								id="password"
								type="password"
								value={password}
								onChange={(e) => setPassword(e.target.value)}
								placeholder="••••••••"
								required
								disabled={loading}
								className="w-full px-4 py-3 border border-gray-300 rounded-md focus:outline-none focus:ring-2 focus:ring-indigo-500 focus:border-transparent disabled:opacity-60 disabled:cursor-not-allowed"
							/>
						</div>

						<button
							type="submit"
							disabled={loading}
							className="w-full py-3 px-4 bg-indigo-600 text-white rounded-md font-medium hover:bg-indigo-700 transition-colors disabled:opacity-60 disabled:cursor-not-allowed"
						>
							{loading ? 'Signing in...' : 'Sign In'}
						</button>
					</form>
				) : (
					<form
						onSubmit={(e) => {
							e.preventDefault();
							handleRegister();
						}}
						className="space-y-6"
					>
						<div>
							<label htmlFor="reg-name" className="block text-sm font-medium text-gray-700 mb-2">
								Name
							</label>
							<input
								id="reg-name"
								type="text"
								value={name}
								onChange={(e) => setName(e.target.value)}
								placeholder="Your Name"
								required
								disabled={loading}
								className="w-full px-4 py-3 border border-gray-300 rounded-md focus:outline-none focus:ring-2 focus:ring-indigo-500 focus:border-transparent disabled:opacity-60 disabled:cursor-not-allowed"
							/>
						</div>

						<div>
							<label htmlFor="reg-email" className="block text-sm font-medium text-gray-700 mb-2">
								Email
							</label>
							<input
								id="reg-email"
								type="email"
								value={email}
								onChange={(e) => setEmail(e.target.value)}
								placeholder="user@example.com"
								required
								disabled={loading}
								className="w-full px-4 py-3 border border-gray-300 rounded-md focus:outline-none focus:ring-2 focus:ring-indigo-500 focus:border-transparent disabled:opacity-60 disabled:cursor-not-allowed"
							/>
						</div>

						<div>
							<label htmlFor="reg-password" className="block text-sm font-medium text-gray-700 mb-2">
								Password
							</label>
							<input
								id="reg-password"
								type="password"
								value={password}
								onChange={(e) => setPassword(e.target.value)}
								placeholder="••••••••"
								required
								minLength={6}
								disabled={loading}
								className="w-full px-4 py-3 border border-gray-300 rounded-md focus:outline-none focus:ring-2 focus:ring-indigo-500 focus:border-transparent disabled:opacity-60 disabled:cursor-not-allowed"
							/>
							<small className="text-xs text-gray-500 mt-1 block">Minimum 6 characters</small>
						</div>

						<button
							type="submit"
							disabled={loading}
							className="w-full py-3 px-4 bg-indigo-600 text-white rounded-md font-medium hover:bg-indigo-700 transition-colors disabled:opacity-60 disabled:cursor-not-allowed"
						>
							{loading ? 'Creating account...' : 'Create Account'}
						</button>
					</form>
				)}
			</div>
		</div>
	);
}

// src/ui/src/routes/login/+page.svelte
<script lang="ts">
	import { goto } from '$app/navigation';
	import { authStore } from '$lib/stores/auth';
	import { api } from '$lib/api';

	let email = '';
	let password = '';
	let name = '';
	let activeTab: 'login' | 'register' = 'login';
	let loading = false;
	let error = '';

	async function handleLogin() {
		if (!email || !password) {
			error = 'Please enter email and password';
			return;
		}

		loading = true;
		error = '';

		try {
			const response = await api.post<{ token: string; user: any }>('/api/v1/auth/login', {
				email,
				password
			});

			await authStore.setToken(response.token);
			goto('/');
		} catch (e: any) {
			error = e.message || 'Login failed. Please try again.';
		} finally {
			loading = false;
		}
	}

	async function handleRegister() {
		if (!email || !password || !name) {
			error = 'Please fill in all fields';
			return;
		}

		if (password.length < 6) {
			error = 'Password must be at least 6 characters';
			return;
		}

		loading = true;
		error = '';

		try {
			const response = await api.post<{ token: string; user: any }>('/api/v1/auth/register', {
				email,
				password,
				name
			});

			await authStore.setToken(response.token);
			goto('/');
		} catch (e: any) {
			error = e.message || 'Registration failed. Please try again.';
		} finally {
			loading = false;
		}
	}
</script>

<div class="login-container">
	<div class="login-card">
		<div class="login-header">
			<div class="brand-header">
				<img src="/gopher.png" alt="AlgoShield" class="brand-icon" />
				<h1>AlgoShield</h1>
			</div>
			<p>Fraud Detection & Anti-Money Laundering</p>
		</div>

		<div class="tabs">
			<button 
				class="tab" 
				class:active={activeTab === 'login'}
				on:click={() => { activeTab = 'login'; error = ''; }}
			>
				Login
			</button>
			<button 
				class="tab" 
				class:active={activeTab === 'register'}
				on:click={() => { activeTab = 'register'; error = ''; }}
			>
				Register
			</button>
		</div>

		{#if error}
			<div class="error-message">
				{error}
			</div>
		{/if}

		{#if activeTab === 'login'}
			<form on:submit|preventDefault={handleLogin} class="login-form">
				<div class="form-group">
					<label for="email">Email</label>
					<input
						id="email"
						type="email"
						bind:value={email}
						placeholder="user@example.com"
						required
						disabled={loading}
					/>
				</div>

				<div class="form-group">
					<label for="password">Password</label>
					<input
						id="password"
						type="password"
						bind:value={password}
						placeholder="••••••••"
						required
						disabled={loading}
					/>
				</div>

				<button type="submit" class="button button-primary full-width" disabled={loading}>
					{loading ? 'Signing in...' : 'Sign In'}
				</button>
			</form>
		{:else}
			<form on:submit|preventDefault={handleRegister} class="login-form">
				<div class="form-group">
					<label for="reg-name">Name</label>
					<input
						id="reg-name"
						type="text"
						bind:value={name}
						placeholder="Your Name"
						required
						disabled={loading}
					/>
				</div>

				<div class="form-group">
					<label for="reg-email">Email</label>
					<input
						id="reg-email"
						type="email"
						bind:value={email}
						placeholder="user@example.com"
						required
						disabled={loading}
					/>
				</div>

				<div class="form-group">
					<label for="reg-password">Password</label>
					<input
						id="reg-password"
						type="password"
						bind:value={password}
						placeholder="••••••••"
						required
						minlength="6"
						disabled={loading}
					/>
					<small>Minimum 6 characters</small>
				</div>

				<button type="submit" class="button button-primary full-width" disabled={loading}>
					{loading ? 'Creating account...' : 'Create Account'}
				</button>
			</form>
		{/if}
	</div>
</div>

<style>
	.login-container {
		min-height: 100vh;
		display: flex;
		align-items: center;
		justify-content: center;
		background: linear-gradient(135deg, #667eea 0%, #764ba2 100%);
		padding: 2rem;
	}

	.login-card {
		background: white;
		border-radius: 12px;
		box-shadow: 0 10px 40px rgba(0, 0, 0, 0.2);
		width: 100%;
		max-width: 450px;
		padding: 2.5rem;
	}

	.login-header {
		text-align: center;
		margin-bottom: 2rem;
	}

	.brand-header {
		display: flex;
		align-items: center;
		justify-content: center;
		gap: 0.75rem;
		margin-bottom: 0.5rem;
	}

	.brand-icon {
		width: 48px;
		height: 48px;
		object-fit: contain;
	}

	.login-header h1 {
		font-size: 2rem;
		margin-bottom: 0.5rem;
		color: var(--text);
	}

	.login-header p {
		color: var(--text-secondary);
		font-size: 0.875rem;
	}

	.tabs {
		display: flex;
		gap: 0.5rem;
		margin-bottom: 2rem;
		border-bottom: 2px solid var(--border);
	}

	.tab {
		flex: 1;
		padding: 0.75rem 1rem;
		border: none;
		background: none;
		cursor: pointer;
		font-size: 1rem;
		color: var(--text-secondary);
		border-bottom: 2px solid transparent;
		margin-bottom: -2px;
		transition: all 0.2s;
	}

	.tab:hover {
		color: var(--text);
	}

	.tab.active {
		color: var(--primary);
		border-bottom-color: var(--primary);
		font-weight: 600;
	}

	.error-message {
		background: #fee;
		border: 1px solid #fcc;
		border-radius: 6px;
		padding: 0.75rem 1rem;
		margin-bottom: 1.5rem;
		color: #c33;
		font-size: 0.875rem;
	}

	.login-form {
		display: flex;
		flex-direction: column;
		gap: 1.5rem;
	}

	.form-group {
		display: flex;
		flex-direction: column;
		gap: 0.5rem;
	}

	.form-group label {
		font-weight: 500;
		color: var(--text);
	}

	.form-group input {
		padding: 0.75rem 1rem;
		border: 1px solid var(--border);
		border-radius: 6px;
		font-size: 1rem;
		transition: border-color 0.2s;
		color: var(--text);
	}

	.form-group input:focus {
		outline: none;
		border-color: var(--primary);
	}

	.form-group input::selection {
		background-color: var(--primary);
		color: white;
	}

	.form-group input::-moz-selection {
		background-color: var(--primary);
		color: white;
	}

	.form-group input:disabled {
		opacity: 0.6;
		cursor: not-allowed;
	}

	.form-group small {
		font-size: 0.75rem;
		color: var(--text-secondary);
	}

	.button {
		padding: 0.875rem 1.5rem;
		border: none;
		border-radius: 6px;
		font-size: 1rem;
		font-weight: 500;
		cursor: pointer;
		transition: all 0.2s;
	}

	.button-primary {
		background: var(--primary);
		color: white;
	}

	.button-primary:hover:not(:disabled) {
		background: #5568d3;
	}

	.button-primary:disabled {
		opacity: 0.6;
		cursor: not-allowed;
	}

	.full-width {
		width: 100%;
	}
</style>
