// src/ui/components/Header.tsx
'use client';

import { useState, useEffect, useRef } from 'react';
import Link from 'next/link';
import { usePathname, useRouter } from 'next/navigation';
import { useAuth } from '@/lib/stores/auth';

export default function Header() {
	const { user, logout } = useAuth();
	const pathname = usePathname();
	const router = useRouter();
	const [showUserMenu, setShowUserMenu] = useState(false);
	const menuRef = useRef<HTMLDivElement>(null);

	const isAdmin = user?.roles?.some((role) => role.name === 'admin') || false;

	useEffect(() => {
		function handleClickOutside(event: MouseEvent) {
			if (menuRef.current && !menuRef.current.contains(event.target as Node)) {
				setShowUserMenu(false);
			}
		}

		document.addEventListener('click', handleClickOutside);
		return () => document.removeEventListener('click', handleClickOutside);
	}, []);

	const handleLogout = async () => {
		await logout();
		router.push('/login');
	};

	if (!user || pathname.startsWith('/login')) {
		return null;
	}

	return (
		<header className="bg-white border-b border-gray-200 shadow-sm">
			<div className="max-w-7xl mx-auto px-8">
				<nav className="py-6 flex items-center justify-between gap-8">
					<div className="flex items-center gap-3">
						<img src="/gopher.png" alt="AlgoShield" className="w-10 h-10 object-contain" />
						<div>
							<h1 className="text-2xl font-semibold text-gray-900">AlgoShield</h1>
							<p className="text-sm text-gray-500">Fraud Detection & Anti-Money Laundering</p>
						</div>
					</div>

					<div className="flex gap-2 flex-1 justify-center">
						<Link
							href="/"
							className={`px-6 py-3 rounded-md text-sm font-medium transition-all ${
								pathname === '/'
									? 'text-indigo-600 bg-indigo-50'
									: 'text-gray-500 hover:text-gray-900 hover:bg-gray-50'
							}`}
						>
							Rules
						</Link>
						<Link
							href="/synthetic-test"
							className={`px-6 py-3 rounded-md text-sm font-medium transition-all ${
								pathname === '/synthetic-test'
									? 'text-indigo-600 bg-indigo-50'
									: 'text-gray-500 hover:text-gray-900 hover:bg-gray-50'
							}`}
						>
							Synthetic Test
						</Link>
						{isAdmin && (
							<Link
								href="/permissions"
								className={`px-6 py-3 rounded-md text-sm font-medium transition-all ${
									pathname === '/permissions'
										? 'text-indigo-600 bg-indigo-50'
										: 'text-gray-500 hover:text-gray-900 hover:bg-gray-50'
								}`}
							>
								Permissions
							</Link>
						)}
					</div>

					<div className="relative" ref={menuRef}>
						<button
							onClick={() => setShowUserMenu(!showUserMenu)}
							className="flex items-center gap-3 px-2 py-2 border border-gray-200 rounded-lg bg-white hover:bg-gray-50 transition-all"
						>
							<div className="w-10 h-10 rounded-full bg-gradient-to-br from-indigo-500 to-purple-600 text-white flex items-center justify-center font-semibold text-lg overflow-hidden">
								{user.picture_url ? (
									<img src={user.picture_url} alt={user.name} className="w-full h-full object-cover" />
								) : (
									user.name.charAt(0).toUpperCase()
								)}
							</div>
							<div className="text-left">
								<div className="text-sm font-medium text-gray-900">{user.name}</div>
								<div className="text-xs text-gray-500">{user.email}</div>
							</div>
							<svg
								className="w-4 h-4 text-gray-500"
								fill="none"
								stroke="currentColor"
								viewBox="0 0 24 24"
							>
								<polyline points="6 9 12 15 18 9"></polyline>
							</svg>
						</button>

						{showUserMenu && (
							<div className="absolute top-full right-0 mt-2 bg-white border border-gray-200 rounded-lg shadow-lg min-w-[240px] z-50">
								<div className="p-4 border-b border-gray-200">
									<div className="font-semibold text-gray-900 mb-1">{user.name}</div>
									<div className="text-sm text-gray-500 mb-2">{user.email}</div>
									<div className="flex flex-wrap gap-2 mt-2">
										{(user.roles || []).map((role) => (
											<span
												key={role.id}
												className="inline-block px-3 py-1 bg-indigo-600 text-white rounded text-xs font-medium"
											>
												{role.name}
											</span>
										))}
									</div>
								</div>
								<button
									onClick={handleLogout}
									className="w-full flex items-center gap-3 px-4 py-3 text-sm text-red-600 hover:bg-gray-50 transition-colors border-t border-gray-200"
								>
									<svg width="16" height="16" viewBox="0 0 24 24" fill="none" stroke="currentColor">
										<path d="M9 21H5a2 2 0 0 1-2-2V5a2 2 0 0 1 2-2h4"></path>
										<polyline points="16 17 21 12 16 7"></polyline>
										<line x1="21" y1="12" x2="9" y2="12"></line>
									</svg>
									Logout
								</button>
							</div>
						)}
					</div>
				</nav>
			</div>
		</header>
	);
}

// src/ui/src/components/Header.vue
<template>
  <header
    v-if="user && !isLoginPage"
    class="fixed top-0 left-0 right-0 border-b border-neutral-800 z-fixed"
    :style="{
      height: 'var(--header-height)',
      backgroundColor: 'var(--color-header-background, #1e1e1e)'
    }"
  >
    <div class="flex items-center justify-between h-full px-8">
      <!-- Left: Logo + Search -->
      <div class="flex items-center gap-6">
        <!-- Logo -->
        <div class="flex items-center gap-2 sm:gap-3">
          <img
            :src="brandingConfig?.icon_url || '/gopher.png'"
            :alt="brandingConfig?.app_name || 'AlgoShield'"
            class="w-6 h-6 sm:w-8 sm:h-8 object-contain flex-shrink-0"
            @error="handleLogoError"
            loading="eager"
          />
          <span class="text-white font-bold text-sm sm:text-lg truncate max-w-[200px] sm:max-w-none">{{ brandingConfig?.app_name || 'AlgoShield' }}</span>
        </div>

        <!-- Global Search -->
        <div class="relative">
          <input
            type="search"
            placeholder="Search transactions, customers, alerts"
            class="w-[400px] h-[36px] px-4 bg-neutral-800 border border-neutral-700 rounded text-sm text-white placeholder-neutral-500 focus:outline-none focus:ring-2 focus:ring-teal-500 focus:ring-offset-2 focus:ring-offset-neutral-800 focus:border-teal-500 transition-all"
          />
        </div>
      </div>

      <!-- Right: Notifications + User -->
      <div class="flex items-center gap-4">
        <!-- Notifications -->
        <button
          class="relative w-10 h-10 flex items-center justify-center rounded-full hover:bg-neutral-800 transition-colors"
        >
          <i class="far fa-bell text-white text-lg"></i>
          <span class="absolute top-1 right-1 w-2 h-2 bg-red-500 rounded-full"></span>
        </button>

        <!-- User Menu -->
        <div class="relative" ref="menuRef">
          <button
            ref="buttonRef"
            @click="handleToggleMenu"
            class="flex items-center gap-2 px-2 py-1 rounded-lg hover:bg-neutral-800 transition-colors"
          >
            <div class="w-8 h-8 rounded-full bg-gradient-to-br from-teal-500 to-teal-600 text-white flex items-center justify-center font-semibold text-sm overflow-hidden">
              <img v-if="user.picture_url" :src="user.picture_url" :alt="user.name" class="w-full h-full object-cover" />
              <span v-else>{{ user.name.charAt(0).toUpperCase() }}</span>
            </div>
            <i class="fas fa-chevron-down text-neutral-400 text-xs"></i>
          </button>

          <!-- Dropdown -->
          <Teleport to="body">
            <div
              v-if="showUserMenu"
              ref="dropdownRef"
              class="fixed bg-white border border-neutral-200 rounded-lg shadow-xl min-w-[220px] z-[1100]"
              :style="{
                top: `${dropdownPosition.top}px`,
                right: `${dropdownPosition.right}px`
              }"
            >
            <div class="p-4 border-b border-neutral-200">
              <div class="font-semibold text-neutral-900 text-sm">{{ user.name }}</div>
              <div class="text-xs text-neutral-500 mt-1">{{ user.email }}</div>
            </div>
            <div class="py-2">
              <router-link
                to="/profile"
                class="flex items-center gap-3 px-4 py-2 text-sm text-neutral-700 hover:bg-neutral-50 transition-colors"
              >
                <i class="fas fa-user w-4"></i>
                <span>Profile</span>
              </router-link>
            </div>
            <div class="border-t border-neutral-200">
              <button
                @click="handleLogout"
                class="w-full flex items-center gap-3 px-4 py-3 text-sm font-medium text-red-600 hover:bg-red-50 transition-colors"
              >
                <i class="fas fa-sign-out-alt w-4"></i>
                <span>Logout</span>
              </button>
            </div>
            </div>
          </Teleport>
        </div>
      </div>
    </div>
  </header>
</template>

<script setup lang="ts">
import { ref, computed, onMounted, onUnmounted, nextTick } from 'vue'
import { useRouter, useRoute } from 'vue-router'
import { useAuthStore } from '@/stores/auth'
import { useBrandingStore } from '@/stores/branding'

const router = useRouter()
const route = useRoute()
const authStore = useAuthStore()
const brandingStore = useBrandingStore()

const showUserMenu = ref(false)
const menuRef = ref<HTMLElement | null>(null)
const buttonRef = ref<HTMLElement | null>(null)
const dropdownRef = ref<HTMLElement | null>(null)
const dropdownPosition = ref({ top: 0, right: 0 })

const user = computed(() => authStore.user)
const isLoginPage = computed(() => route.path.startsWith('/login'))
const brandingConfig = computed(() => brandingStore.config)

const updateDropdownPosition = () => {
  if (buttonRef.value) {
    const rect = buttonRef.value.getBoundingClientRect()
    dropdownPosition.value = {
      top: rect.bottom + 8, // 8px = mt-2
      right: window.innerWidth - rect.right
    }
  }
}

const handleToggleMenu = async () => {
  showUserMenu.value = !showUserMenu.value
  if (showUserMenu.value) {
    await nextTick()
    updateDropdownPosition()
  }
}

const handleLogout = async () => {
  await authStore.logout()
  router.push('/login')
}

const handleLogoError = (event: Event) => {
  // Fallback to default logo if custom logo fails to load
  const img = event.target as HTMLImageElement
  img.src = '/gopher.png'
}

function handleClickOutside(event: MouseEvent) {
  const target = event.target as Node
  const clickedInsideButton = buttonRef.value && buttonRef.value.contains(target)
  const clickedInsideDropdown = dropdownRef.value && dropdownRef.value.contains(target)
  
  if (!clickedInsideButton && !clickedInsideDropdown) {
    showUserMenu.value = false
  }
}

onMounted(() => {
  document.addEventListener('click', handleClickOutside)
  window.addEventListener('resize', updateDropdownPosition)
  window.addEventListener('scroll', updateDropdownPosition, true)
})

onUnmounted(() => {
  document.removeEventListener('click', handleClickOutside)
  window.removeEventListener('resize', updateDropdownPosition)
  window.removeEventListener('scroll', updateDropdownPosition, true)
})
</script>
