// src/ui/app/synthetic-test/page.tsx
'use client';

import { useState } from 'react';

interface Field {
	name: string;
	type: 'string' | 'number' | 'boolean' | 'date' | 'uuid' | 'email' | 'ip';
	required: boolean;
	format?: string;
}

interface TestResult {
	timestamp: string;
	data: any;
	score: number;
	action: string;
	status: 'success' | 'error';
}

const fieldTypes = [
	{ value: 'string', label: 'String' },
	{ value: 'number', label: 'Number' },
	{ value: 'boolean', label: 'Boolean' },
	{ value: 'date', label: 'Date/Time' },
	{ value: 'uuid', label: 'UUID' },
	{ value: 'email', label: 'Email' },
	{ value: 'ip', label: 'IP Address' },
];

export default function SyntheticTestPage() {
	const [fields, setFields] = useState<Field[]>([
		{ name: 'transaction_id', type: 'uuid', required: true },
		{ name: 'amount', type: 'number', required: true },
		{ name: 'user_email', type: 'email', required: true },
	]);
	const [testResults, setTestResults] = useState<TestResult[]>([]);
	const [loading, setLoading] = useState(false);
	const [shouldStop, setShouldStop] = useState(false);
	const [currentProgress, setCurrentProgress] = useState(0);
	const [numberOfEvents, setNumberOfEvents] = useState(1);
	const [showAddField, setShowAddField] = useState(false);
	const [newField, setNewField] = useState<Partial<Field>>({ name: '', type: 'string', required: true });

	function addField() {
		if (newField.name && newField.type) {
			setFields([...fields, newField as Field]);
			setNewField({ name: '', type: 'string', required: true });
			setShowAddField(false);
		}
	}

	function removeField(index: number) {
		setFields(fields.filter((_, i) => i !== index));
	}

	function generateValue(field: Field): any {
		switch (field.type) {
			case 'uuid':
				return crypto.randomUUID();
			case 'email':
				return `user${Math.floor(Math.random() * 10000)}@example.com`;
			case 'number':
				return Math.floor(Math.random() * 10000) + 100;
			case 'boolean':
				return Math.random() > 0.5;
			case 'date':
				return new Date().toISOString();
			case 'ip':
				return `${Math.floor(Math.random() * 256)}.${Math.floor(Math.random() * 256)}.${Math.floor(Math.random() * 256)}.${Math.floor(Math.random() * 256)}`;
			case 'string':
			default:
				return `value_${Math.random().toString(36).substring(7)}`;
		}
	}

	function generateSyntheticData(): any {
		const data: any = {};
		fields.forEach((field) => {
			data[field.name] = generateValue(field);
		});
		return data;
	}

	async function runTest() {
		setLoading(true);
		setShouldStop(false);
		setCurrentProgress(0);
		setTestResults([]);

		try {
			for (let i = 0; i < numberOfEvents; i++) {
				if (shouldStop) {
					console.log('Test stopped by user');
					break;
				}

				const syntheticData = generateSyntheticData();

				// Simulate API call
				await new Promise((resolve) => setTimeout(resolve, 300));

				const mockScore = Math.floor(Math.random() * 100);
				const mockAction = mockScore > 80 ? 'block' : mockScore > 50 ? 'review' : 'allow';

				setTestResults((prev) => [
					...prev,
					{
						timestamp: new Date().toISOString(),
						data: syntheticData,
						score: mockScore,
						action: mockAction,
						status: 'success',
					},
				]);

				setCurrentProgress(i + 1);
			}
		} catch (error) {
			console.error('Test failed:', error);
		}

		setLoading(false);
		setCurrentProgress(0);
	}

	function stopTest() {
		setShouldStop(true);
	}

	function exportResults() {
		const dataStr = JSON.stringify(testResults, null, 2);
		const blob = new Blob([dataStr], { type: 'application/json' });
		const url = URL.createObjectURL(blob);
		const link = document.createElement('a');
		link.href = url;
		link.download = `synthetic-test-${Date.now()}.json`;
		link.click();
		URL.revokeObjectURL(url);
	}

	function clearResults() {
		setTestResults([]);
	}

	return (
		<div className="max-w-7xl mx-auto px-8">
			<div className="mb-8">
				<h2 className="text-3xl font-semibold mb-2">Synthetic Data Testing</h2>
				<p className="text-gray-500">Generate and test synthetic events with custom field schemas</p>
			</div>

			<div className="grid grid-cols-1 md:grid-cols-2 gap-6 mb-6">
				{/* Field Configuration Panel */}
				<div className="bg-white rounded-lg border border-gray-200 p-6">
					<h3 className="text-xl font-semibold mb-2">Event Schema</h3>
					<p className="text-sm text-gray-500 mb-6">Define the fields for your synthetic events</p>

					<div className="space-y-3">
						{fields.map((field, index) => (
							<div key={index} className="flex items-center justify-between p-3 bg-gray-50 border border-gray-200 rounded-md">
								<div className="flex-1">
									<div className="font-medium text-gray-900 flex items-center gap-2">
										{field.name}
										{field.required && (
											<span className="px-2 py-0.5 bg-yellow-500 text-white rounded text-xs">Required</span>
										)}
									</div>
									<div className="text-sm text-gray-500">{field.type}</div>
								</div>
								<button
									onClick={() => removeField(index)}
									className="text-red-600 text-xl leading-none hover:opacity-80"
									title="Remove field"
								>
									✕
								</button>
							</div>
						))}

						{showAddField ? (
							<div className="p-4 bg-gray-50 border-2 border-dashed border-gray-300 rounded-md space-y-3">
								<input
									type="text"
									value={newField.name || ''}
									onChange={(e) => setNewField({ ...newField, name: e.target.value })}
									placeholder="Field name"
									className="w-full px-4 py-2 border border-gray-300 rounded-md focus:outline-none focus:ring-2 focus:ring-indigo-500"
								/>
								<select
									value={newField.type || 'string'}
									onChange={(e) => setNewField({ ...newField, type: e.target.value as Field['type'] })}
									className="w-full px-4 py-2 border border-gray-300 rounded-md focus:outline-none focus:ring-2 focus:ring-indigo-500"
								>
									{fieldTypes.map((type) => (
										<option key={type.value} value={type.value}>
											{type.label}
										</option>
									))}
								</select>
								<label className="flex items-center gap-2 text-sm">
									<input
										type="checkbox"
										checked={newField.required || false}
										onChange={(e) => setNewField({ ...newField, required: e.target.checked })}
									/>
									Required
								</label>
								<div className="flex gap-2">
									<button
										onClick={addField}
										className="px-4 py-2 bg-indigo-600 text-white rounded text-sm hover:bg-indigo-700 transition-colors"
									>
										Add
									</button>
									<button
										onClick={() => setShowAddField(false)}
										className="px-4 py-2 border border-gray-300 rounded text-sm hover:bg-gray-50 transition-colors"
									>
										Cancel
									</button>
								</div>
							</div>
						) : (
							<button
								onClick={() => setShowAddField(true)}
								className="w-full px-4 py-2 border border-dashed border-gray-300 rounded text-sm text-gray-500 hover:border-indigo-500 hover:text-indigo-600 transition-colors"
							>
								+ Add Field
							</button>
						)}
					</div>
				</div>

				{/* Test Configuration Panel */}
				<div className="bg-white rounded-lg border border-gray-200 p-6">
					<h3 className="text-xl font-semibold mb-2">Test Configuration</h3>
					<p className="text-sm text-gray-500 mb-6">Configure and run your tests</p>

					<div className="mb-6">
						<label htmlFor="numEvents" className="block text-sm font-medium text-gray-700 mb-2">
							Number of Events
						</label>
						<input
							id="numEvents"
							type="number"
							min="1"
							max="1000"
							value={numberOfEvents}
							onChange={(e) => setNumberOfEvents(parseInt(e.target.value) || 1)}
							disabled={loading}
							className="w-full px-4 py-3 border border-gray-300 rounded-md focus:outline-none focus:ring-2 focus:ring-indigo-500 disabled:opacity-60"
						/>
					</div>

					{loading ? (
						<>
							<div className="mb-4 p-4 bg-gray-50 border border-gray-200 rounded-md">
								<div className="flex justify-between items-center mb-3 text-sm">
									<span>Processing events...</span>
									<span className="font-semibold text-indigo-600">
										{currentProgress} / {numberOfEvents}
									</span>
								</div>
								<div className="w-full h-2 bg-gray-200 rounded-full overflow-hidden">
									<div
										className="h-full bg-gradient-to-r from-indigo-600 to-purple-600 transition-all duration-300"
										style={{ width: `${(currentProgress / numberOfEvents) * 100}%` }}
									></div>
								</div>
							</div>

							<button
								onClick={stopTest}
								className="w-full py-3 px-4 bg-red-600 text-white rounded-md font-medium hover:bg-red-700 transition-colors"
							>
								⏹ Stop Test
							</button>
						</>
					) : (
						<button
							onClick={runTest}
							disabled={fields.length === 0}
							className="w-full py-3 px-4 bg-indigo-600 text-white rounded-md font-medium hover:bg-indigo-700 transition-colors disabled:opacity-60 disabled:cursor-not-allowed"
						>
							▶ Run Test
						</button>
					)}

					{testResults.length > 0 && (
						<>
							<div className="grid grid-cols-2 gap-4 mt-6 p-6 bg-gray-50 rounded-md">
								<div className="text-center">
									<div className="text-3xl font-bold text-indigo-600">{testResults.length}</div>
									<div className="text-sm text-gray-500 mt-1">Events Tested</div>
								</div>
								<div className="text-center">
									<div className="text-3xl font-bold text-indigo-600">
										{testResults.filter((r) => r.action === 'block').length}
									</div>
									<div className="text-sm text-gray-500 mt-1">Blocked</div>
								</div>
								<div className="text-center">
									<div className="text-3xl font-bold text-indigo-600">
										{testResults.filter((r) => r.action === 'review').length}
									</div>
									<div className="text-sm text-gray-500 mt-1">Review</div>
								</div>
								<div className="text-center">
									<div className="text-3xl font-bold text-indigo-600">
										{testResults.filter((r) => r.action === 'allow').length}
									</div>
									<div className="text-sm text-gray-500 mt-1">Allowed</div>
								</div>
							</div>

							<div className="flex gap-2 mt-4">
								<button
									onClick={exportResults}
									className="flex-1 px-4 py-2 border border-gray-300 rounded text-sm hover:bg-gray-50 transition-colors"
								>
									Export Results
								</button>
								<button
									onClick={clearResults}
									className="flex-1 px-4 py-2 border border-gray-300 rounded text-sm hover:bg-gray-50 transition-colors"
								>
									Clear
								</button>
							</div>
						</>
					)}
				</div>
			</div>

			{/* Results Panel */}
			{testResults.length > 0 && (
				<div className="bg-white rounded-lg border border-gray-200 p-6">
					<h3 className="text-xl font-semibold mb-6">Test Results</h3>

					<div className="space-y-4">
						{testResults.map((result, index) => (
							<div key={index} className="border border-gray-200 rounded-md p-4">
								<div className="flex items-center gap-4 mb-2">
									<span className="font-bold text-gray-500">#{index + 1}</span>
									<span className="text-sm text-gray-500">
										{new Date(result.timestamp).toLocaleTimeString()}
									</span>
									<span
										className={`px-3 py-1 rounded-full text-xs font-medium ${
											result.action === 'block'
												? 'bg-red-500 text-white'
												: result.action === 'review'
													? 'bg-yellow-500 text-white'
													: 'bg-green-500 text-white'
										}`}
									>
										{result.action}
									</span>
									<span className="ml-auto font-medium">Score: {result.score}</span>
								</div>
								<details className="mt-3">
									<summary className="cursor-pointer text-sm text-indigo-600 hover:text-indigo-700 select-none">
										View Event Data
									</summary>
									<pre className="mt-3 p-4 bg-gray-50 rounded border border-gray-200 overflow-x-auto text-sm">
										{JSON.stringify(result.data, null, 2)}
									</pre>
								</details>
							</div>
						))}
					</div>
				</div>
			)}
		</div>
	);
}

// src/ui/src/routes/synthetic-test/+page.svelte
<script lang="ts">
	import { onMount } from 'svelte';

	interface Field {
		name: string;
		type: 'string' | 'number' | 'boolean' | 'date' | 'uuid' | 'email' | 'ip';
		required: boolean;
		format?: string;
	}

	interface TestResult {
		timestamp: string;
		data: any;
		score: number;
		action: string;
		status: 'success' | 'error';
	}

	let fields: Field[] = [
		{ name: 'transaction_id', type: 'uuid', required: true },
		{ name: 'amount', type: 'number', required: true },
		{ name: 'user_email', type: 'email', required: true }
	];

	let testResults: TestResult[] = [];
	let loading = false;
	let shouldStop = false;
	let currentProgress = 0;
	let numberOfEvents = 1;
	let showAddField = false;
	let newField: Partial<Field> = { name: '', type: 'string', required: true };

	const fieldTypes = [
		{ value: 'string', label: 'String' },
		{ value: 'number', label: 'Number' },
		{ value: 'boolean', label: 'Boolean' },
		{ value: 'date', label: 'Date/Time' },
		{ value: 'uuid', label: 'UUID' },
		{ value: 'email', label: 'Email' },
		{ value: 'ip', label: 'IP Address' }
	];

	function addField() {
		if (newField.name && newField.type) {
			fields = [...fields, newField as Field];
			newField = { name: '', type: 'string', required: true };
			showAddField = false;
		}
	}

	function removeField(index: number) {
		fields = fields.filter((_, i) => i !== index);
	}

	function generateValue(field: Field): any {
		switch (field.type) {
			case 'uuid':
				return crypto.randomUUID();
			case 'email':
				return `user${Math.floor(Math.random() * 10000)}@example.com`;
			case 'number':
				return Math.floor(Math.random() * 10000) + 100;
			case 'boolean':
				return Math.random() > 0.5;
			case 'date':
				return new Date().toISOString();
			case 'ip':
				return `${Math.floor(Math.random() * 256)}.${Math.floor(Math.random() * 256)}.${Math.floor(Math.random() * 256)}.${Math.floor(Math.random() * 256)}`;
			case 'string':
			default:
				return `value_${Math.random().toString(36).substring(7)}`;
		}
	}

	function generateSyntheticData(): any {
		const data: any = {};
		fields.forEach(field => {
			data[field.name] = generateValue(field);
		});
		return data;
	}

	async function runTest() {
		loading = true;
		shouldStop = false;
		currentProgress = 0;
		testResults = [];

		try {
			for (let i = 0; i < numberOfEvents; i++) {
				// Check if user requested stop
				if (shouldStop) {
					console.log('Test stopped by user');
					break;
				}

				const syntheticData = generateSyntheticData();
				
				// Simulate API call
				await new Promise(resolve => setTimeout(resolve, 300));
				
				const mockScore = Math.floor(Math.random() * 100);
				const mockAction = mockScore > 80 ? 'block' : mockScore > 50 ? 'review' : 'allow';
				
				testResults = [...testResults, {
					timestamp: new Date().toISOString(),
					data: syntheticData,
					score: mockScore,
					action: mockAction,
					status: 'success'
				}];

				currentProgress = i + 1;
			}
		} catch (error) {
			console.error('Test failed:', error);
		}

		loading = false;
		currentProgress = 0;
	}

	function stopTest() {
		shouldStop = true;
	}

	function exportResults() {
		const dataStr = JSON.stringify(testResults, null, 2);
		const blob = new Blob([dataStr], { type: 'application/json' });
		const url = URL.createObjectURL(blob);
		const link = document.createElement('a');
		link.href = url;
		link.download = `synthetic-test-${Date.now()}.json`;
		link.click();
		URL.revokeObjectURL(url);
	}

	function clearResults() {
		testResults = [];
	}
</script>

<div class="container">
	<div class="header-section">
		<div>
			<h2>Synthetic Data Testing</h2>
			<p>Generate and test synthetic events with custom field schemas</p>
		</div>
	</div>

	<div class="grid">
		<!-- Field Configuration Panel -->
		<div class="card">
			<h3>Event Schema</h3>
			<p class="subtitle">Define the fields for your synthetic events</p>

			<div class="fields-list">
				{#each fields as field, index}
					<div class="field-item">
						<div class="field-info">
							<div class="field-name">
								{field.name}
								{#if field.required}
									<span class="required-badge">Required</span>
								{/if}
							</div>
							<div class="field-type">{field.type}</div>
						</div>
						<button 
							class="remove-btn"
							on:click={() => removeField(index)}
							title="Remove field"
						>
							✕
						</button>
					</div>
				{/each}

				{#if showAddField}
					<div class="add-field-form">
						<input
							class="input"
							type="text"
							bind:value={newField.name}
							placeholder="Field name"
						/>
						<select class="select" bind:value={newField.type}>
							{#each fieldTypes as type}
								<option value={type.value}>{type.label}</option>
							{/each}
						</select>
						<label class="checkbox-label">
							<input type="checkbox" bind:checked={newField.required} />
							Required
						</label>
						<div class="button-group">
							<button class="button button-sm" on:click={addField}>Add</button>
							<button class="button button-sm" on:click={() => showAddField = false}>Cancel</button>
						</div>
					</div>
				{:else}
					<button 
						class="button button-outline"
						on:click={() => showAddField = true}
					>
						+ Add Field
					</button>
				{/if}
			</div>
		</div>

		<!-- Test Configuration Panel -->
		<div class="card">
			<h3>Test Configuration</h3>
			<p class="subtitle">Configure and run your tests</p>

			<div class="form-group">
				<label for="numEvents">Number of Events</label>
				<input
					id="numEvents"
					class="input"
					type="number"
					min="1"
					max="1000"
					bind:value={numberOfEvents}
					disabled={loading}
				/>
			</div>

			{#if loading}
				<div class="progress-section">
					<div class="progress-info">
						<span>Processing events...</span>
						<span class="progress-count">{currentProgress} / {numberOfEvents}</span>
					</div>
					<div class="progress-bar">
						<div 
							class="progress-fill" 
							style="width: {(currentProgress / numberOfEvents) * 100}%"
						></div>
					</div>
				</div>

				<button 
					class="button button-danger full-width"
					on:click={stopTest}
				>
					⏹ Stop Test
				</button>
			{:else}
				<button 
					class="button button-primary full-width"
					on:click={runTest}
					disabled={fields.length === 0}
				>
					▶ Run Test
				</button>
			{/if}

			{#if testResults.length > 0}
				<div class="test-stats">
					<div class="stat">
						<div class="stat-value">{testResults.length}</div>
						<div class="stat-label">Events Tested</div>
					</div>
					<div class="stat">
						<div class="stat-value">
							{testResults.filter(r => r.action === 'block').length}
						</div>
						<div class="stat-label">Blocked</div>
					</div>
					<div class="stat">
						<div class="stat-value">
							{testResults.filter(r => r.action === 'review').length}
						</div>
						<div class="stat-label">Review</div>
					</div>
					<div class="stat">
						<div class="stat-value">
							{testResults.filter(r => r.action === 'allow').length}
						</div>
						<div class="stat-label">Allowed</div>
					</div>
				</div>

				<div class="button-group">
					<button class="button button-outline" on:click={exportResults}>
						Export Results
					</button>
					<button class="button button-outline" on:click={clearResults}>
						Clear
					</button>
				</div>
			{/if}
		</div>
	</div>

	<!-- Results Panel -->
	{#if testResults.length > 0}
		<div class="card results-card">
			<h3>Test Results</h3>
			
			<div class="results-list">
				{#each testResults as result, index}
					<div class="result-item">
						<div class="result-header">
							<span class="result-number">#{index + 1}</span>
							<span class="result-time">{new Date(result.timestamp).toLocaleTimeString()}</span>
							<span class="badge badge-{result.action}">{result.action}</span>
							<span class="result-score">Score: {result.score}</span>
						</div>
						<details class="result-details">
							<summary>View Event Data</summary>
							<pre>{JSON.stringify(result.data, null, 2)}</pre>
						</details>
					</div>
				{/each}
			</div>
		</div>
	{/if}
</div>

<style>
	.header-section {
		margin-bottom: 2rem;
	}

	h2 {
		font-size: 2rem;
		margin-bottom: 0.5rem;
	}

	h3 {
		font-size: 1.25rem;
		margin-bottom: 0.5rem;
	}

	.subtitle {
		color: var(--text-secondary);
		font-size: 0.875rem;
		margin-bottom: 1.5rem;
	}

	.grid {
		display: grid;
		grid-template-columns: repeat(auto-fit, minmax(350px, 1fr));
		gap: 1.5rem;
		margin-bottom: 1.5rem;
	}

	.fields-list {
		display: flex;
		flex-direction: column;
		gap: 0.75rem;
	}

	.field-item {
		display: flex;
		align-items: center;
		justify-content: space-between;
		padding: 0.75rem;
		background: var(--surface);
		border: 1px solid var(--border);
		border-radius: 6px;
	}

	.field-info {
		flex: 1;
	}

	.field-name {
		font-weight: 500;
		display: flex;
		align-items: center;
		gap: 0.5rem;
	}

	.field-type {
		color: var(--text-secondary);
		font-size: 0.875rem;
	}

	.required-badge {
		font-size: 0.75rem;
		padding: 0.125rem 0.5rem;
		background: var(--warning);
		color: white;
		border-radius: 3px;
	}

	.remove-btn {
		padding: 0.25rem 0.5rem;
		border: none;
		background: none;
		color: var(--danger);
		cursor: pointer;
		font-size: 1.25rem;
		line-height: 1;
	}

	.remove-btn:hover {
		color: var(--danger);
		opacity: 0.8;
	}

	.add-field-form {
		display: flex;
		flex-direction: column;
		gap: 0.75rem;
		padding: 1rem;
		background: var(--surface);
		border: 2px dashed var(--border);
		border-radius: 6px;
	}

	.checkbox-label {
		display: flex;
		align-items: center;
		gap: 0.5rem;
		font-size: 0.875rem;
	}

	.button-group {
		display: flex;
		gap: 0.5rem;
	}

	.button-sm {
		padding: 0.5rem 1rem;
		font-size: 0.875rem;
	}

	.full-width {
		width: 100%;
	}

	.progress-section {
		margin-bottom: 1rem;
		padding: 1rem;
		background: var(--surface);
		border-radius: 6px;
		border: 1px solid var(--border);
	}

	.progress-info {
		display: flex;
		justify-content: space-between;
		align-items: center;
		margin-bottom: 0.75rem;
		font-size: 0.875rem;
	}

	.progress-count {
		font-weight: 600;
		color: var(--primary);
	}

	.progress-bar {
		width: 100%;
		height: 8px;
		background: var(--border);
		border-radius: 4px;
		overflow: hidden;
	}

	.progress-fill {
		height: 100%;
		background: linear-gradient(90deg, var(--primary), #764ba2);
		transition: width 0.3s ease;
	}

	.test-stats {
		display: grid;
		grid-template-columns: repeat(2, 1fr);
		gap: 1rem;
		margin-top: 1.5rem;
		padding: 1.5rem;
		background: var(--surface);
		border-radius: 6px;
	}

	.stat {
		text-align: center;
	}

	.stat-value {
		font-size: 2rem;
		font-weight: 700;
		color: var(--primary);
	}

	.stat-label {
		font-size: 0.875rem;
		color: var(--text-secondary);
		margin-top: 0.25rem;
	}

	.results-card {
		margin-top: 1.5rem;
	}

	.results-list {
		display: flex;
		flex-direction: column;
		gap: 1rem;
	}

	.result-item {
		border: 1px solid var(--border);
		border-radius: 6px;
		padding: 1rem;
	}

	.result-header {
		display: flex;
		align-items: center;
		gap: 1rem;
		margin-bottom: 0.5rem;
	}

	.result-number {
		font-weight: 700;
		color: var(--text-secondary);
	}

	.result-time {
		color: var(--text-secondary);
		font-size: 0.875rem;
	}

	.result-score {
		margin-left: auto;
		font-weight: 500;
	}

	.badge-allow {
		background: var(--success);
	}

	.badge-review {
		background: var(--warning);
	}

	.badge-block {
		background: var(--danger);
	}

	.result-details {
		margin-top: 0.75rem;
	}

	.result-details summary {
		cursor: pointer;
		color: var(--primary);
		font-size: 0.875rem;
		user-select: none;
	}

	.result-details pre {
		margin-top: 0.75rem;
		padding: 1rem;
		background: var(--surface);
		border-radius: 4px;
		overflow-x: auto;
		font-size: 0.875rem;
	}
</style>
