// src/ui/src/routes/permissions/+page.svelte
<script lang="ts">
	import { onMount } from 'svelte';
	import { api } from '$lib/api';
	import { authStore } from '$lib/stores/auth';
	import { goto } from '$app/navigation';

	interface User {
		id: string;
		email: string;
		name: string;
		picture_url?: string;
		active: boolean;
		roles: Role[];
	}

	interface Role {
		id: string;
		name: string;
		description: string;
	}

	let users: User[] = [];
	let roles: Role[] = [];
	let loading = true;
	let error = '';
	let selectedUser: User | null = null;
	let showRoleModal = false;

	onMount(async () => {
		// Check if user is admin
		const currentUser = await new Promise<User | null>((resolve) => {
			const unsubscribe = authStore.subscribe((user) => {
				unsubscribe();
				resolve(user);
			});
		});

		const isAdmin = currentUser?.roles?.some((r) => r.name === 'admin');
		if (!isAdmin) {
			goto('/');
			return;
		}

		await loadData();
	});

	async function loadData() {
		try {
			loading = true;
			error = '';
			const [usersRes, rolesRes] = await Promise.all([
				api.get<{ users: User[] }>('/api/v1/permissions/users'),
				api.get<{ roles: Role[] }>('/api/v1/permissions/roles')
			]);
			users = usersRes.users;
			roles = rolesRes.roles;
		} catch (e: any) {
			error = e.message || 'Failed to load data';
		} finally {
			loading = false;
		}
	}

	async function toggleUserActive(user: User) {
		try {
			await api.put(`/api/v1/permissions/users/${user.id}/active`, {
				active: !user.active
			});
			await loadData();
		} catch (e: any) {
			error = e.message || 'Failed to update user';
		}
	}

	function openRoleModal(user: User) {
		selectedUser = user;
		showRoleModal = true;
	}

	function closeRoleModal() {
		selectedUser = null;
		showRoleModal = false;
	}

	async function assignRole(roleId: string) {
		if (!selectedUser) return;
		try {
			await api.post(`/api/v1/permissions/users/${selectedUser.id}/roles`, {
				role_id: roleId
			});
			await loadData();
			closeRoleModal();
		} catch (e: any) {
			error = e.message || 'Failed to assign role';
		}
	}

	async function removeRole(userId: string, roleId: string) {
		try {
			await api.delete(`/api/v1/permissions/users/${userId}/roles/${roleId}`);
			await loadData();
		} catch (e: any) {
			error = e.message || 'Failed to remove role';
		}
	}

	function hasRole(user: User, roleName: string): boolean {
		return user.roles?.some((r) => r.name === roleName) || false;
	}
</script>

<div class="permissions-container">
	<div class="header">
		<h1>Permissions Management</h1>
		<p>Manage users, roles, and permissions</p>
	</div>

	{#if error}
		<div class="error-banner">
			{error}
			<button on:click={() => (error = '')}>×</button>
		</div>
	{/if}

	{#if loading}
		<div class="loading">Loading...</div>
	{:else}
		<div class="users-table">
			<table>
				<thead>
					<tr>
						<th>User</th>
						<th>Email</th>
						<th>Roles</th>
						<th>Status</th>
						<th>Actions</th>
					</tr>
				</thead>
				<tbody>
					{#each users as user}
						<tr>
							<td>
								<div class="user-cell">
									{#if user.picture_url}
										<img src={user.picture_url} alt={user.name} class="user-avatar-small" />
									{:else}
										<div class="user-avatar-small">{user.name.charAt(0).toUpperCase()}</div>
									{/if}
									<span>{user.name}</span>
								</div>
							</td>
							<td>{user.email}</td>
							<td>
								<div class="roles-cell">
									{#each user.roles || [] as role}
										<span class="role-tag">
											{role.name}
											<button
												class="remove-role"
												on:click={() => removeRole(user.id, role.id)}
												title="Remove role"
											>
												×
											</button>
										</span>
									{/each}
									<button class="add-role-btn" on:click={() => openRoleModal(user)}>
										+ Add Role
									</button>
								</div>
							</td>
							<td>
								<span class="status-badge" class:active={user.active} class:inactive={!user.active}>
									{user.active ? 'Active' : 'Inactive'}
								</span>
							</td>
							<td>
								<button
									class="toggle-btn"
									on:click={() => toggleUserActive(user)}
									class:deactivate={user.active}
								>
									{user.active ? 'Deactivate' : 'Activate'}
								</button>
							</td>
						</tr>
					{/each}
				</tbody>
			</table>
		</div>
	{/if}
</div>

{#if showRoleModal && selectedUser}
	<div class="modal-overlay" on:click={closeRoleModal}>
		<div class="modal" on:click|stopPropagation>
			<div class="modal-header">
				<h2>Assign Role to {selectedUser.name}</h2>
				<button class="close-btn" on:click={closeRoleModal}>×</button>
			</div>
			<div class="modal-body">
				<div class="roles-list">
					{#each roles as role}
						{#if !hasRole(selectedUser, role.name)}
							<button class="role-option" on:click={() => assignRole(role.id)}>
								<div class="role-name">{role.name}</div>
								<div class="role-description">{role.description}</div>
							</button>
						{/if}
					{/each}
				</div>
			</div>
		</div>
	</div>
{/if}

<style>
	.permissions-container {
		max-width: 1400px;
		margin: 0 auto;
		padding: 2rem;
	}

	.header {
		margin-bottom: 2rem;
	}

	.header h1 {
		font-size: 2rem;
		margin-bottom: 0.5rem;
		color: var(--text);
	}

	.header p {
		color: var(--text-secondary);
	}

	.error-banner {
		background: #fee;
		border: 1px solid #fcc;
		border-radius: 6px;
		padding: 1rem;
		margin-bottom: 1.5rem;
		color: #c33;
		display: flex;
		justify-content: space-between;
		align-items: center;
	}

	.error-banner button {
		background: none;
		border: none;
		font-size: 1.5rem;
		cursor: pointer;
		color: #c33;
	}

	.loading {
		text-align: center;
		padding: 3rem;
		color: var(--text-secondary);
	}

	.users-table {
		background: white;
		border-radius: 8px;
		box-shadow: 0 2px 8px rgba(0, 0, 0, 0.1);
		overflow: hidden;
	}

	table {
		width: 100%;
		border-collapse: collapse;
	}

	thead {
		background: var(--surface);
	}

	th {
		padding: 1rem;
		text-align: left;
		font-weight: 600;
		color: var(--text);
		border-bottom: 2px solid var(--border);
	}

	td {
		padding: 1rem;
		border-bottom: 1px solid var(--border);
	}

	tr:hover {
		background: var(--surface);
	}

	.user-cell {
		display: flex;
		align-items: center;
		gap: 0.75rem;
	}

	.user-avatar-small {
		width: 32px;
		height: 32px;
		border-radius: 50%;
		background: linear-gradient(135deg, #667eea 0%, #764ba2 100%);
		color: white;
		display: flex;
		align-items: center;
		justify-content: center;
		font-weight: 600;
		font-size: 0.875rem;
		overflow: hidden;
	}

	.user-avatar-small img {
		width: 100%;
		height: 100%;
		object-fit: cover;
	}

	.roles-cell {
		display: flex;
		flex-wrap: wrap;
		gap: 0.5rem;
		align-items: center;
	}

	.role-tag {
		display: inline-flex;
		align-items: center;
		gap: 0.5rem;
		padding: 0.375rem 0.75rem;
		background: var(--primary);
		color: white;
		border-radius: 4px;
		font-size: 0.875rem;
		font-weight: 500;
	}

	.remove-role {
		background: rgba(255, 255, 255, 0.3);
		border: none;
		border-radius: 50%;
		width: 18px;
		height: 18px;
		cursor: pointer;
		color: white;
		font-size: 1rem;
		line-height: 1;
		display: flex;
		align-items: center;
		justify-content: center;
		padding: 0;
	}

	.remove-role:hover {
		background: rgba(255, 255, 255, 0.5);
	}

	.add-role-btn {
		padding: 0.375rem 0.75rem;
		border: 1px dashed var(--border);
		background: white;
		border-radius: 4px;
		cursor: pointer;
		font-size: 0.875rem;
		color: var(--text-secondary);
		transition: all 0.2s;
	}

	.add-role-btn:hover {
		border-color: var(--primary);
		color: var(--primary);
	}

	.status-badge {
		padding: 0.375rem 0.75rem;
		border-radius: 4px;
		font-size: 0.875rem;
		font-weight: 500;
	}

	.status-badge.active {
		background: #d4edda;
		color: #155724;
	}

	.status-badge.inactive {
		background: #f8d7da;
		color: #721c24;
	}

	.toggle-btn {
		padding: 0.5rem 1rem;
		border: 1px solid var(--border);
		background: white;
		border-radius: 4px;
		cursor: pointer;
		font-size: 0.875rem;
		transition: all 0.2s;
	}

	.toggle-btn:hover {
		background: var(--surface);
	}

	.toggle-btn.deactivate {
		color: var(--danger);
		border-color: var(--danger);
	}

	.modal-overlay {
		position: fixed;
		top: 0;
		left: 0;
		right: 0;
		bottom: 0;
		background: rgba(0, 0, 0, 0.5);
		display: flex;
		align-items: center;
		justify-content: center;
		z-index: 1000;
	}

	.modal {
		background: white;
		border-radius: 8px;
		box-shadow: 0 4px 20px rgba(0, 0, 0, 0.3);
		max-width: 500px;
		width: 90%;
		max-height: 80vh;
		overflow: auto;
	}

	.modal-header {
		display: flex;
		justify-content: space-between;
		align-items: center;
		padding: 1.5rem;
		border-bottom: 1px solid var(--border);
	}

	.modal-header h2 {
		margin: 0;
		font-size: 1.5rem;
	}

	.close-btn {
		background: none;
		border: none;
		font-size: 2rem;
		cursor: pointer;
		color: var(--text-secondary);
		line-height: 1;
		padding: 0;
		width: 32px;
		height: 32px;
		display: flex;
		align-items: center;
		justify-content: center;
	}

	.modal-body {
		padding: 1.5rem;
	}

	.roles-list {
		display: flex;
		flex-direction: column;
		gap: 0.75rem;
	}

	.role-option {
		padding: 1rem;
		border: 1px solid var(--border);
		border-radius: 6px;
		background: white;
		cursor: pointer;
		text-align: left;
		transition: all 0.2s;
	}

	.role-option:hover {
		border-color: var(--primary);
		background: var(--surface);
	}

	.role-name {
		font-weight: 600;
		color: var(--text);
		margin-bottom: 0.25rem;
	}

	.role-description {
		font-size: 0.875rem;
		color: var(--text-secondary);
	}
</style>

// src/ui/app/permissions/page.tsx
'use client';

import { useEffect, useState } from 'react';
import { useRouter } from 'next/navigation';
import { useAuth } from '@/lib/stores/auth';
import { api } from '@/lib/api';

interface Role {
	id: string;
	name: string;
	description: string;
}

interface User {
	id: string;
	email: string;
	name: string;
	picture_url?: string;
	active: boolean;
	roles: Role[];
}

export default function PermissionsPage() {
	const { user: currentUser } = useAuth();
	const router = useRouter();
	const [users, setUsers] = useState<User[]>([]);
	const [roles, setRoles] = useState<Role[]>([]);
	const [loading, setLoading] = useState(true);
	const [error, setError] = useState('');
	const [selectedUser, setSelectedUser] = useState<User | null>(null);
	const [showRoleModal, setShowRoleModal] = useState(false);

	useEffect(() => {
		const isAdmin = currentUser?.roles?.some((r) => r.name === 'admin');
		if (currentUser && !isAdmin) {
			router.push('/');
			return;
		}
		if (currentUser) {
			loadData();
		}
	}, [currentUser, router]);

	async function loadData() {
		try {
			setLoading(true);
			setError('');
			const [usersRes, rolesRes] = await Promise.all([
				api.get<{ users: User[] }>('/api/v1/permissions/users'),
				api.get<{ roles: Role[] }>('/api/v1/roles'),
			]);
			setUsers(usersRes.users);
			setRoles(rolesRes.roles);
		} catch (e: any) {
			setError(e.message || 'Failed to load data');
		} finally {
			setLoading(false);
		}
	}

	async function toggleUserActive(user: User) {
		try {
			await api.put(`/api/v1/permissions/users/${user.id}/active`, {
				active: !user.active,
			});
			await loadData();
		} catch (e: any) {
			setError(e.message || 'Failed to update user');
		}
	}

	function openRoleModal(user: User) {
		setSelectedUser(user);
		setShowRoleModal(true);
	}

	function closeRoleModal() {
		setSelectedUser(null);
		setShowRoleModal(false);
	}

	async function assignRole(roleId: string) {
		if (!selectedUser) return;
		try {
			await api.post(`/api/v1/permissions/users/${selectedUser.id}/roles`, {
				role_id: roleId,
			});
			await loadData();
			closeRoleModal();
		} catch (e: any) {
			setError(e.message || 'Failed to assign role');
		}
	}

	async function removeRole(userId: string, roleId: string) {
		try {
			await api.delete(`/api/v1/permissions/users/${userId}/roles/${roleId}`);
			await loadData();
		} catch (e: any) {
			setError(e.message || 'Failed to remove role');
		}
	}

	function hasRole(user: User, roleName: string): boolean {
		return user.roles?.some((r) => r.name === roleName) || false;
	}

	return (
		<div className="max-w-7xl mx-auto px-8">
			<div className="mb-8">
				<h1 className="text-3xl font-semibold mb-2">Permissions Management</h1>
				<p className="text-gray-500">Manage users, roles, and permissions</p>
			</div>

			{error && (
				<div className="bg-red-50 border border-red-200 rounded-md p-4 mb-6 text-red-600 flex justify-between items-center">
					<span>{error}</span>
					<button onClick={() => setError('')} className="text-2xl leading-none">
						×
					</button>
				</div>
			)}

			{loading ? (
				<div className="text-center py-12 text-gray-500">Loading...</div>
			) : (
				<div className="bg-white rounded-lg border border-gray-200 overflow-hidden shadow-sm">
					<table className="w-full border-collapse">
						<thead className="bg-gray-50">
							<tr>
								<th className="px-4 py-4 text-left font-semibold text-gray-900 border-b-2 border-gray-200">User</th>
								<th className="px-4 py-4 text-left font-semibold text-gray-900 border-b-2 border-gray-200">Email</th>
								<th className="px-4 py-4 text-left font-semibold text-gray-900 border-b-2 border-gray-200">Roles</th>
								<th className="px-4 py-4 text-left font-semibold text-gray-900 border-b-2 border-gray-200">Status</th>
								<th className="px-4 py-4 text-left font-semibold text-gray-900 border-b-2 border-gray-200">Actions</th>
							</tr>
						</thead>
						<tbody>
							{users.map((user) => (
								<tr key={user.id} className="hover:bg-gray-50">
									<td className="px-4 py-4 border-b border-gray-200">
										<div className="flex items-center gap-3">
											{user.picture_url ? (
												<img
													src={user.picture_url}
													alt={user.name}
													className="w-8 h-8 rounded-full object-cover"
												/>
											) : (
												<div className="w-8 h-8 rounded-full bg-gradient-to-br from-indigo-500 to-purple-600 text-white flex items-center justify-center font-semibold text-sm">
													{user.name.charAt(0).toUpperCase()}
												</div>
											)}
											<span>{user.name}</span>
										</div>
									</td>
									<td className="px-4 py-4 border-b border-gray-200 text-gray-900">{user.email}</td>
									<td className="px-4 py-4 border-b border-gray-200">
										<div className="flex flex-wrap gap-2 items-center">
											{(user.roles || []).map((role) => (
												<span
													key={role.id}
													className="inline-flex items-center gap-2 px-3 py-1.5 bg-indigo-600 text-white rounded text-sm font-medium"
												>
													{role.name}
													<button
														onClick={() => removeRole(user.id, role.id)}
														className="bg-white bg-opacity-30 rounded-full w-4.5 h-4.5 flex items-center justify-center text-xs hover:bg-opacity-50 transition-colors"
														title="Remove role"
													>
														×
													</button>
												</span>
											))}
											<button
												onClick={() => openRoleModal(user)}
												className="px-3 py-1.5 border border-dashed border-gray-300 bg-white rounded text-sm text-gray-500 hover:border-indigo-500 hover:text-indigo-600 transition-colors"
											>
												+ Add Role
											</button>
										</div>
									</td>
									<td className="px-4 py-4 border-b border-gray-200">
										<span
											className={`px-3 py-1.5 rounded text-sm font-medium ${
												user.active
													? 'bg-green-100 text-green-800'
													: 'bg-red-100 text-red-800'
											}`}
										>
											{user.active ? 'Active' : 'Inactive'}
										</span>
									</td>
									<td className="px-4 py-4 border-b border-gray-200">
										<button
											onClick={() => toggleUserActive(user)}
											className={`px-4 py-2 border rounded text-sm transition-colors ${
												user.active
													? 'text-red-600 border-red-600 hover:bg-red-50'
													: 'text-gray-700 border-gray-300 hover:bg-gray-50'
											}`}
										>
											{user.active ? 'Deactivate' : 'Activate'}
										</button>
									</td>
								</tr>
							))}
						</tbody>
					</table>
				</div>
			)}

			{showRoleModal && selectedUser && (
				<div
					className="fixed inset-0 bg-black bg-opacity-50 flex items-center justify-center z-50"
					onClick={closeRoleModal}
				>
					<div
						className="bg-white rounded-lg max-w-md w-full mx-4 max-h-[80vh] overflow-auto shadow-xl"
						onClick={(e) => e.stopPropagation()}
					>
						<div className="flex justify-between items-center p-6 border-b border-gray-200">
							<h2 className="text-2xl font-semibold">Assign Role to {selectedUser.name}</h2>
							<button
								onClick={closeRoleModal}
								className="text-3xl leading-none text-gray-500 hover:text-gray-700 w-8 h-8 flex items-center justify-center"
							>
								×
							</button>
						</div>
						<div className="p-6">
							<div className="flex flex-col gap-3">
								{roles.map((role) => {
									if (hasRole(selectedUser, role.name)) return null;
									return (
										<button
											key={role.id}
											onClick={() => assignRole(role.id)}
											className="p-4 border border-gray-200 rounded-md bg-white text-left hover:border-indigo-500 hover:bg-gray-50 transition-all"
										>
											<div className="font-semibold text-gray-900 mb-1">{role.name}</div>
											<div className="text-sm text-gray-500">{role.description}</div>
										</button>
									);
								})}
							</div>
						</div>
					</div>
				</div>
			)}
		</div>
	);
}
